---
#Start apache service
- name: Enable apache service
  service: 
    name: httpd 
    enabled: yes
- name: Starting apache service
  service: 
    name: httpd 
    state: started
- name: restart
  notify:
    - restart apache service
