---
#Start apache service
- name: Enable apache service
  service: 
    name: httpd 
    enabled: yes

- name: Starting apache service
  service: 
    name: httpd 
    state: started

- name: restart service
  shell: systemctl status httpd
  notify:
    - restart apache service
