---
#Start apache service
- name: Enable apache service
  service: 
    name: httpd 
    enabled: yes

- name: Starting apache service
  service: 
    name: httpd 
    state: started

- name: restart service
  shell: systemctl start httpd
  notify:
    - restart apache service
  tags:
    - always
- name: restart the service again
  shell: systemctl start httpd
  
- name: Starting apache service again
  service: 
    name: httpd 
    state: started
